#!/bin/bash

# 🎃 Haunted VS Code Extension - Quick Start Guide 🎃

echo "👻 =============================================== 👻"
echo "   Welcome to the HAUNTED VS CODE Extension!"
echo "👻 =============================================== 👻"
echo ""
echo "🔮 What this extension does:"
echo "   • Adds ghost cursor trails that follow your movements"
echo "   • Randomly flickers themes for spooky atmosphere"
echo "   • Shows 'spooky sound effects' when you delete code"
echo "   • Includes exorcism cheat codes to banish spirits"
echo "   • Perfect for Halloween coding sessions!"
echo ""
echo "🚀 How to test the extension:"
echo "   1. Make sure you're in VS Code"
echo "   2. Press F5 to launch Extension Development Host"
echo "   3. In the new window, open TESTING.md"
echo "   4. Start typing and moving your cursor around"
echo "   5. Try deleting some code to see effects"
echo "   6. Type 'EXORCISE' to banish the spirits"
echo ""
echo "⚙️ Configuration:"
echo "   • Open Settings (Ctrl/Cmd + ,)"
echo "   • Search for 'haunted'"
echo "   • Adjust intensity and toggle effects"
echo ""
echo "🆘 Emergency Exorcism:"
echo "   • Type any of these words: EXORCISE, BANISH, PURIFY"
echo "   • Or use Ctrl+Shift+Alt+E (Cmd+Shift+Alt+E on Mac)"
echo ""
echo "📦 Extension Structure:"
echo "   ✅ package.json - Extension manifest"
echo "   ✅ src/ - TypeScript source code"
echo "   ✅ out/ - Compiled JavaScript"
echo "   ✅ README.md - Full documentation"
echo "   ✅ TESTING.md - Test scenarios"
echo "   ✅ CHANGELOG.md - Version history"
echo ""
echo "🎯 Ready to haunt your VS Code? Press F5 in VS Code!"
echo ""
echo "👻 Happy Halloween Coding! 🎃"
